# Generated by Django 4.0.4 on 2022-05-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BindingOptions',
            new_name='BindingOption',
        ),
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
