# Generated by Django 4.0.4 on 2022-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_bookpublish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublish',
            name='binding',
            field=models.CharField(blank=True, default='Binding', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookpublish',
            name='cover_finish',
            field=models.CharField(blank=True, default='Binding', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookpublish',
            name='paper',
            field=models.CharField(blank=True, default='Binding', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='audience',
            field=models.TextField(blank=True, default='audience', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='bisac_category1',
            field=models.CharField(blank=True, default='bisac_category1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='bisac_category2',
            field=models.CharField(blank=True, default='bisac_category2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='bisac_category3',
            field=models.CharField(blank=True, default='bisac_category3', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='category',
            field=models.CharField(blank=True, default='category', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='color',
            field=models.CharField(blank=True, default='color', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='contributor_notes',
            field=models.TextField(blank=True, default='contributor_notes', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='description',
            field=models.TextField(blank=True, default='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='global_upload',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='isbn',
            field=models.CharField(blank=True, default='isbn', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='keywords',
            field=models.TextField(blank=True, default='keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='language',
            field=models.CharField(blank=True, default='language', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='size',
            field=models.CharField(blank=True, default='size', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='table_of_contents',
            field=models.TextField(blank=True, default='table_of_contents', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookpublish',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=200, null=True),
        ),
    ]
