# Generated by Django 4.0.4 on 2022-05-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_bookpublish_binding_bookpublish_cover_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublish',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
