# Generated by Django 4.0.4 on 2022-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_alter_bookprint_author_alter_bookprint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprint',
            name='binding',
            field=models.CharField(blank=True, default='default data binding', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='category',
            field=models.CharField(blank=True, default='default data category', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='color',
            field=models.CharField(blank=True, default='default data color', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='cover_finish',
            field=models.CharField(blank=True, default='default data coverFinish', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='description',
            field=models.TextField(blank=True, default='default data description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='isbn',
            field=models.CharField(blank=True, default='default data isbn', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='language',
            field=models.CharField(blank=True, default='default data language', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='queue_status',
            field=models.CharField(blank=True, default='queued', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='size',
            field=models.CharField(blank=True, default='default data size', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookprint',
            name='title',
            field=models.CharField(blank=True, default='default data title', max_length=200, null=True),
        ),
    ]
