# Generated by Django 4.0.4 on 2022-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_bookprint_binding_alter_bookprint_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpublish',
            old_name='revenue',
            new_name='currentRevenue',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='currentRevenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='totalRevenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookpublish',
            name='totalRevenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
