# Generated by Django 4.0.4 on 2022-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_rename_revenue_bookpublish_currentrevenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='total_books',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
